language: node_js
before_install:
  - npm config set depth 0
  - npm install --global npm@3
script:
  - npm run lint
  - npm run test
node_js:
  - 6
  - 5
  - 4
notifications:
  email: false
sudo: false
